version: "3.9"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgsql-data:/var/lib/postgresql

  postgres_test:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}_test
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    ports:
      - 5433:5432
    volumes:
      - pgsql-data:/var/lib/postgresql
  
volumes:
    pgsql-data: